version: '2'
services:
  database:
    image: mysql:5.7
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123
    restart: always
    volumes:
      - /volume1/docker/mysql-archivesspace:/var/lib/mysql
  archivesspace:
    image: archivesspace/archivesspace:latest
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8089:8089"
      - "8090:8090"
    depends_on:
      - database
    restart: always
    environment:
      APPCONFIG_DB_URL: 'jdbc:mysql://database:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123'
    links:
      - database
